admin_email: manuel.pastor@upf.edu
admin_name: Manuel Pastor
config_status: true
homepage: http://phi.upf.edu
model_repository_path: /home/jcgomez/projects/internals/flame/eye_irritation
space_repository_path: C:\Users\mpastor\Documents\soft\flame\flame\spaces
predictions_repository_path: /home/jcgomez/projects/internals/flame/eye_irritation
provider: UPF (Pompeu Fabra University)
