admin_email: manuel.pastor@upf.edu
admin_name: Manuel Pastor
config_status: true
homepage: http://phi.upf.edu
model_repository_path: E:\synced\internals\flame\eye_irritation\models
predictions_repository_path: E:\synced\internals\flame\eye_irritation\predictions
provider: UPF (Pompeu Fabra University)
space_repository_path: E:\synced\internals\flame\eye_irritation\spaces
